[package]
name = "liquid-derive"
version = "0.23.0"
authors = ["Pedro Gonçalo Correia <goncalerta@gmail.com>"]
description = "The liquid templating language for Rust"
readme = "README.md"
categories = ["template-engine"]
keywords = ["liquid", "template", "templating", "language", "html"]
license = "MIT OR Apache-2.0"
edition = "2018"
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
proc-quote = "0.4"
proc-macro2 = "1.0"
