[package]
name = "liquid-core"
version = "0.23.0"
authors = ["Ed Page <eopage@gmail.com>"]
description = "Core liquid functionality"
repository = "https://github.com/cobalt-org/liquid-rust/tree/master/crate/core"
documentation = "https://docs.rs/liquid-core"
readme = "README.md"
categories = ["template-engine"]
keywords = ["liquid", "template", "templating", "language", "html"]
license = "MIT OR Apache-2.0"
edition = "2018"
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[dependencies]
anymap2 = "0.13"
itertools = "0.10.0"
num-traits = "0.2"
pest = "2.0"
pest_derive = "2.0"

# Exposed in API
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
kstring = "1.0"
liquid-derive = { version = "^0.23.0", path = "../derive", optional = true }

[dev-dependencies]
difference = "2.0"
serde_yaml = "0.9"

[features]
default = []
derive = ["liquid-derive"]
